PFAS_GROUPS = [
    (1, "Perfluoroalkyl carboxylic acids", [{"group_smiles":"C(=O)O[H]",'n':1,'mode':'attach','neighbours':['C']}], 'Perfluoroalkyl'),
    (2, "Polyfluoroalkyl carboxylic acid", [{"group_smiles":"C(=O)O[H]",'n':1,'mode':'attach','neighbours':['C']}],  'Polyfluoroalkyl'),
    (3, "Perfluoroalkyl dicarboxylic acids", [{"group_smiles":"C(=O)O[H]",'n':2,'mode':'attach','neighbours':['C']}], 'Perfluoroalkyl'),
    (4, "Perfluoroalkylether carboxylic acids", [{"group_smiles":"C(=O)O[H]",'n':1,'mode':'attach','neighbours':['C']},
                                                 {"group_smiles":"O",'n':1,'mode':'insert'}], 'Perfluoroalkyl'),
    (5, "Polyfluoroalkylether carboxylic acid", [{"group_smiles":"C(=O)O[H]",'n':1,'mode':'attach','neighbours':['C']},
                                                 {"group_smiles":"O",'n':1,'mode':'insert'}], 'Polyfluoroalkyl'),
    (6, "Perfluoroalkyl sulfonic acids", [{"group_smiles":"S(=O)(=O)O[H]", 'n':1, 'mode':'attach'}], 'Perfluoroalkyl'),
    (7, "Polyfluoroalkyl sulfonic acid", [{"group_smiles":"S(=O)(=O)O[H]", 'n':1, 'mode':'attach'}], 'Polyfluoroalkyl'),
    (8, "Perfluoroalkyl disulfonic acids", [{"group_smiles":"S(=O)(=O)O[H]", 'n':2, 'mode':'attach'}], 'Perfluoroalkyl'),
    (9, "Perfluoroalkylether sulfonic acids", [
        {"group_smiles":"S(=O)(=O)O[H]", 'n':1, 'mode':'attach'},
        {"group_smiles":"O", 'n':1, 'mode':'insert'}
    ], 'Perfluoroalkyl'),
    (10, "Polyfluoroalkylether sulfonic acid", [
        {"group_smiles":"S(=O)(=O)O[H]", 'n':1, 'mode':'attach'},
        {"group_smiles":"O", 'n':1, 'mode':'insert'}
    ], 'Polyfluoroalkyl'),
    (11, "Perfluoroalkyl sulfinic acids", [{"group_smiles":"S(=O)O[H]", 'n':1, 'mode':'attach'}], 'Perfluoroalkyl'),
    (12, "Perfluoroalkyl phosphonic acids", [{"group_smiles":"P(=O)(O[H])O[H]", 'n':1, 'mode':'attach'}], 'Perfluoroalkyl'),
    (13, "Perfluoroalkyl phosphinic acids", [{"group_smiles":"P(=O)O[H]", 'n':1, 'mode':'attach'}], 'Perfluoroalkyl'),
    (14, "Perfluoroalkyl alcohols", [{"group_smiles":"O", 'n':"[1,3]", 'mode':'attach'}], 'Perfluoroalkyl'),
    (15, "fluorotelomer alcohols", [{"items":[{"smiles":"C","n":"[2,5]"},{"smiles":"O[H]","n":1}], 'n':1, 'mode':'attach'}], 'Perfluoroalkyl'),
    (16, "Perfluoropolyethers", [{"group_smiles":"O", 'n':"[2,4]", 'mode':'insert'}], 'Perfluoroalkyl'),
    (17, "Hydrofluoroethers", [{"group_smiles":"O", 'n':"[1,5]", 'mode':'insert'}], 'Polyfluoroalkyl'),
    (18, "Perfluoroalkene", [{"group_smiles":"C(F)=C(F)", 'n':1, 'mode':'insert'}], 'Perfluoroalkyl'),
    (19, "Hydrofluoroolefins", [{"group_smiles":"C(F)=C([H])", 'n':1, 'mode':'insert'}], 'Polyfluoroalkyl'),
    (20, "Hydrofluorocarbons", [{"group_smiles":"C(F)[H]", 'n':1, 'mode':'insert'}], 'Polyfluoroalkyl'),
    (21, "Semi-fluorinated alkanes", [{"group_smiles":"C(F)[H]", 'n':1, 'mode':'insert'}], 'Polyfluoroalkyl'),
    (22, "Side-chain fluorinated aromatics", [{"group_smiles":"c1ccccc1", 'n':1, 'mode':'attach'}], 'Polyfluoroalkyl'),
    (23, "Perfluoroalkane", [{"group_smiles":"C(F)(F)", 'n':1, 'mode':'insert'}], 'Perfluoroalkyl'),
    (24, "Perfluoroalkyl-tert-amines", [{"group_smiles":"N(C(F)(F)C(F)(F)F)(C(F)(F)C(F)(F)F)", 'n':1, 'mode':'attach'}], 'Perfluoroalkyl'),
    (25, "Perfluoroalkyl iodides", [{"group_smiles":"I", 'n':"[1,3]", 'mode':'attach'}], 'Perfluoroalkyl'),
    (26, "Perfluoroalkane sulfonyl fluorides", [{"group_smiles":"S(=O)(=O)F", 'n':1, 'mode':'attach'}], 'Perfluoroalkyl'),
    (27, "Perfluoroalkyl ketones", [{"group_smiles":"C(=O)", 'n':1, 'mode':'insert'}], 'Perfluoroalkyl'),
    (28, "Semi-fluoroalkyl ketones", [{"group_smiles":"C(=O)", 'n':1, 'mode':'insert'}], 'Polyfluoroalkyl'),
    (29, 'alcohol', f"O[H]",'attach'),
    (30, 'ketone', f"C(=O)",'insert'),
    (31, 'ether', f"O",'insert'),
    (32, 'ester', f"C(=O)OC",'insert'),
    (33, 'carboxylic acid', f"C(=O)O",'attach'),
    (34, 'amide', f"C(=O)N",'insert'),
    (35, 'acyl halide', f"C(=O)Cl",'attach'),
    (36, 'sulfonic acid', f"S(=O)(=O)O",'attach'),
    (37, 'sulfenic acid', f"SO[H]",'attach'),
    (38, 'sulfinic acid', f"S(=O)O[H]",'attach'),
    (39, 'phosphonic acid', f"P(=O)(O)O",'attach'),
    (40, 'phosphinic acid', f"P(=O)O",'attach'),
    (41, 'ethene', f"C(F)=C(F)",'insert'),
    (41, 'ethene', f"C(F)(F)C(C)=C(F)",'insert'),
    (42, 'iodide', f"C(F)I",'insert'),
    (43, 'sulfonamide', f"S(=O)(=O)N",'insert'),
    (44, 'azole', f"c1ncc[nH]1",'attach'),
    (45, 'azine', f"c1ncccc1",'attach'),
    (46, 'benzodioxole', f"c1ccc2OC(F)(F)Oc2c1",'attach'),
    (47, 'amine', f"N",'insert'),
    (48, 'alkane', 'C(F)(F)', 'insert'),
    (49, 'alkene', 'C(F)=C(F)','insert'),
    (50, 'alkyne', f"C#C",'insert'),
    (51, 'Side-chain aromatics', "c1ccccc1",'attach')
]